# Site
repository: https://github.com/AakashMallik/resume
favicon: images/favicon.ico

# Personal info
name: Aakash S. Mallik
title: Software Engineer
email: humble.discipulus@gmail.com (personal)
phone: +91-7081311219 (personal)
# website: Your website (eg. https://google.com)(optional)

# Dark Mode (true/false/never)
darkmode: true

# =======================================================================
#                           Social links
# =======================================================================
twitter_username: humble_d98
github_username:  AakashMallik
stackoverflow_username: "8895077"
# dribbble_username: jekyll
facebook_username: humble.discipulus
# flickr_username: jekyll
instagram_username: buddhist_nomad
linkedin_username: aakash-mallik-5b8198132
# xing_username: jekyll
# pinterest_username: jekyll
youtube_username: channel/UCmR0ItZcuYlh81JHXVS1yWQ
# googleplus_username: +jekyll
# orcid_username: 0000-0000-0000-0000

# =======================================================================
#                      Additional icon links
# =======================================================================
additional_links:
# - title: Link name
#   icon: Font Awesome brand icon name (eg. fa-twitter) (https://fontawesome.com/icons?d=gallery&s=brands&m=free)
#   url: Link url (eg. https://google.com)
# - title: another link
#   icon: font awesome brand icon name (eg. fa-twitter) (https://fontawesome.com/icons?d=gallery&s=brands&m=free)
#   url: Link url (eg. https://google.com)

# Google Analytics and Tag Manager
# Using more than one of these may cause issues with reporting
# gtm: "GTM-0000000"
# gtag: "UA-00000000-0"
# google_analytics: "UA-00000000-0"

# =======================================================================
#                            About Section
# =======================================================================
# about_title: About Me (Use this to override about section title)
about_profile_image: images/profile_1.jpg
about_content: | # this will include new lines to allow paragraphs
  **Aakash Mallik** aka **humble_D** is a software engineer at Samsung R&D. He is currently working on a patented idea implementation that uses Swarm Intelligence at its core.
  He has worked with several startups during his college years thus enjoys the culture of fast paced engineering. He loves working in teams and gels with
  new folks with ease; communication happens to be one of his strong suits. He spends a lot of time working on personal projects; trying out new technologies
  in the process. He also has a passion for teaching and loves to mentor students who like a bit of challenge. 

  These days he uses his free time on Kaggle competitions trying to glue Neural Networks and Elegant development skills into beautiful robust Pytorch pipelines.
  He also spends his weekends working as a consultant for international startups.

# =======================================================================
#                          Projects Section
# =======================================================================
# projects_title: Projects #(Use this to override about projects section title)

# =======================================================================
#                          Experience Section
# =======================================================================
# experience_title: Experience #(Use this to override about experience section title)

# =======================================================================
#                          Education Section
# =======================================================================
# education_title: Education #(Use this to override about education section title)

# =======================================================================
#                            More Section
# =======================================================================
# more_title: A Little More About Me #(Use this to override about more section title)
more_content: | # this will include new lines to allow paragraphs
  This is where you can write a little more about yourself. You could title this section **Interests** and include some of your other interests.

  Or you could title it **Skills** and write a bit more about things that make you more desirable, like *leadership* or *teamwork*

# =======================================================================
#                               Footer
# =======================================================================
footer_show_references: true

# =======================================================================
#                           Build settings
# =======================================================================
# theme: modern-resume-theme (Use this is you are hosting your resume yourself)
# remote_theme: sproogen/modern-resume-theme (Use this if you are hosting your resume on GitHub)

sass:
  sass_dir: _sass
  style: compressed

plugins:
 - jekyll-seo-tag

exclude : [
  "Gemfile",
  "Gemfile.lock",
  "node_modules",
  "vendor/bundle/",
  "vendor/cache/",
  "vendor/gems/",
  "vendor/ruby/",
  "lib/",
  "scripts/",
  "docker-compose.yml",
  ]
